[project]
name = "lightdirection-estimation"
description = "A ComfyUI custom node for estimating light direction and quality from normal maps using luma masking. The system analyzes surface normals to infer lighting information for downstream tasks like adaptive relighting, directional masking, or stylized effects."
version = "1.0.0"
license = {file = "LICENSE"} 
# classifiers = [
#     # For OS-independent nodes (works on all operating systems)
#     "Operating System :: OS Independent",
#
#     # OR for OS-specific nodes, specify the supported systems:
#     "Operating System :: Microsoft :: Windows",  # Windows specific
#     "Operating System :: POSIX :: Linux",  # Linux specific
#     "Operating System :: MacOS",  # macOS specific
#
#     # GPU Accelerator support. Pick the ones that are supported by your extension.
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
#     "Environment :: GPU :: AMD ROCm",       # AMD ROCm support
#     "Environment :: GPU :: Intel Arc",      # Intel Arc support
#     "Environment :: NPU :: Huawei Ascend",  # Huawei Ascend support
#     "Environment :: GPU :: Apple Metal",    # Apple Metal support
# ]

dependencies = ["torch>=1.9.0", "matplotlib>=3.7.0", "numpy>=1.21.0", "Pillow>=8.0.0"]

[project.urls]
Repository = "https://github.com/APZmedia/Comfyui-LightDirection-estimation"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/APZmedia/Comfyui-LightDirection-estimation/wiki"
"Bug Tracker" = "https://github.com/APZmedia/Comfyui-LightDirection-estimation/issues"

[tool.comfy]
PublisherId = ""
DisplayName = "Comfyui-LightDirection-estimation"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

